const errorCodes = [
  // quest errors
  "QUEST_TITLE_REQUIRED",
  "QUEST_KIND_INVALID",
  "QUEST_STATUS_INVALID",
  "QUEST_STATUS_ALREADY_PAUSED",
  "QUEST_STATUS_ALREADY_IDLED",
  "QUEST_STATUS_ALREADY_ABANDONED",
  "QUEST_STATUS_ALREADY_COMPLETED",
  "QUEST_STATUS_ALREADY_REMOVED",
  "QUEST_STATUS_CANNOT_BE_INITIALIZED_WITH_REMOVED",
  "QUEST_STATUS_CANNOT_BE_INITIALIZED_WITH_IDLED",

  // note errors
  "NOTE_TEXT_REQUIRED",

  // progress errors
  "PROGRESS_TEXT_REQUIRED"
] as const
export type ErrorCode = (typeof errorCodes)[number]
